### ISSUE TITLE
loglevel wrong

### ISSUE THREAD

**Issue by flwzz** [qiniu/typed-less-modules#15]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Expected Behavior 
tlm can work when loglevel set to `error`

## Current Behavior
the next error will output and no `*.less.d.ts` will be generated when all the '.less.d.ts' been renoved and then  `loglevel` is set to `error`( `rm src/**/*.less.d.ts & npx tlm 'src/**/*.less' -e default -n none -l error -w`) :
![image](https://user-images.githubusercontent.com/48706298/125032002-e62cc080-e0bf-11eb-9b85-8cb3fbb7439c.png)
if i set the loglevel to `vebose`, '.less.d.ts' files will be output normally.

## Your Environment
node 12.18.0

- Version used: ^1.01
- Operating System and versions: ubuntu_20.04
- Link to your project:

**Comment by nighca** [comment]
Close due to repo archived, see details in https://github.com/qiniu/typed-less-modules/issues/30#issuecomment-2298113479
