### ISSUE TITLE
Import alias doesn't work with React app

### ISSUE THREAD

**Issue by KarelHrkal** [qiniu/typed-less-modules#20]
## Expected Behavior

TLM options `--includePaths` and `--aliases` should worked correctly when TLM is used in a typescript React app.

## Current Behavior

If you clone this repo and run the "basic example" command, then it works fine. But if you create a React typescript app and run the same command (after copying the example folder of course), then you get the following error:

```
Cannot find module 'alias' from 'C:\Projekty\test\react-app-tlm\examples\basic\feature-b' (examples/basic/feature-b/style.less[1:0])
'variables' wasn't found. Tried - examples\basic\feature-a\variables.less,npm://variables,npm://variables.less,variables.less (examples/basic/feature-a/style.less[1:0])
```

## Possible Solution

Maybe this has nothing to do with React and it only works when you clone this repo (and it runs in "developer mode"), and doesn't work when you install it with yarn or npm.

## Steps to Reproduce (for bugs)

1. Create a new typescript React app with `yarn create react-app my-app --template typescript`
2. Install LESS and TLM with `yarn add -D less typed-less-modules`
3. Copy the "examples" folder from this repo to the new project
4. Run the example command: `yarn tlm "examples/basic/**/*.less" --includePaths examples/basic/core --aliases.~alias examples/basic/core/variables`

## Context

I'm trying to generate typed style annotations for a typescript React app.

## Your Environment

Host OS: Windows 10
IDE Used: VS Code
Commands ran from: Windows Power Shell

- Version used: Repo cloned from current master branch, module installed: typed-less-modules@1.0.1
- Operating System and versions: Windows 10
- Link to your project: (no link, follow the 4 steps to reproduce to get the same repo as I have)

**Comment by nighca** [comment]
Close due to repo archived, see details in https://github.com/qiniu/typed-less-modules/issues/30#issuecomment-2298113479
