### ISSUE TITLE
why is the directory param required when using a config file?

### ISSUE THREAD

**Issue by ReinisV** [qiniu/typed-less-modules#29]
running command
```
tlm --watch
```
with config file `tlm.config.js` in the root of the node project:
```
const path = require("path");

module.exports = {
  pattern: "./src/**/*.module.less",
  aliases: {
    "@": path.resolve(__dirname, "src")
  },
  nameFormat: 'none',
  exportType: 'default'
};
```

returns the error `Not enough non-option arguments: got 0, need at least 1`.

why do we need to pass a directory, if it is already configured in the configuration file?

**Comment by nighca** [comment]
Close due to repo archived, see details in https://github.com/qiniu/typed-less-modules/issues/30#issuecomment-2298113479
